# Generated by Django 4.2.23 on 2025-07-02 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaServicio',
            fields=[
                ('Id_Area', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('Id_Equipo', models.AutoField(primary_key=True, serialize=False)),
                ('Equ_Placa_Serie', models.CharField(max_length=100, unique=True)),
                ('Area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chequeos.areaservicio')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sof_Nombre', models.CharField(max_length=100)),
                ('Sof_Tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Usu_Nombre', models.CharField(max_length=100)),
                ('Usu_Cargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspecificacionesEquipo',
            fields=[
                ('Id_Especificacion', models.AutoField(primary_key=True, serialize=False)),
                ('Esp_Procesador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Procesador')),
                ('Esp_Disco_Duro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Disco Duro')),
                ('Esp_Tipo_Disco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Disco')),
                ('Esp_Sistema_Operativo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operativo')),
                ('Esp_Version_SO', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión del SO')),
                ('Esp_Licencia_SO', models.CharField(blank=True, max_length=100, null=True, verbose_name='Licencia del SO')),
                ('Esp_Memoria_RAM', models.CharField(blank=True, max_length=100, null=True, verbose_name='Memoria RAM')),
                ('Esp_Tarjeta_Video', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarjeta de Video')),
                ('Esp_Puertos_Disponibles', models.TextField(blank=True, null=True, verbose_name='Puertos Disponibles')),
                ('Esp_SO_Actualizado', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Tiene actualizaciones del SO?')),
                ('Esp_Antivirus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Antivirus Instalado')),
                ('Esp_Antivirus_Actualizado', models.CharField(blank=True, max_length=100, null=True, verbose_name='¿Antivirus actualizado?')),
                ('Esp_Software_Instalado', models.TextField(blank=True, null=True, verbose_name='Software Instalado')),
                ('Esp_Estado_Equipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado del Equipo')),
                ('Esp_Estado_Bateria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado de la Batería')),
                ('Esp_Observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones generales')),
                ('Id_Equipo', models.OneToOneField(db_column='Id_Equipo', on_delete=django.db.models.deletion.CASCADE, to='chequeos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equiposoftware_set', to='chequeos.equipo')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chequeos.software')),
            ],
        ),
        migrations.CreateModel(
            name='Chequeo',
            fields=[
                ('Id_Chequeo', models.AutoField(primary_key=True, serialize=False)),
                ('Che_Fecha_Chequeo', models.DateField()),
                ('Che_Observaciones', models.TextField(blank=True, null=True)),
                ('Id_Equipo', models.ForeignKey(db_column='Id_Equipo', on_delete=django.db.models.deletion.CASCADE, to='chequeos.equipo')),
                ('Id_Usuario', models.ForeignKey(db_column='Id_Usuario', on_delete=django.db.models.deletion.CASCADE, to='chequeos.usuario')),
            ],
        ),
    ]
