# Generated by Django 4.2.23 on 2025-07-08 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaServicio',
            fields=[
                ('Id_Area', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('Id_Equipo', models.AutoField(primary_key=True, serialize=False)),
                ('Equ_Placa_Serie', models.CharField(max_length=100)),
                ('Area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chequeos.areaservicio')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sof_Nombre', models.CharField(max_length=100)),
                ('Sof_Tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Usu_Nombre', models.CharField(max_length=100)),
                ('Usu_Cargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EspecificacionesEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Esp_Procesador', models.CharField(max_length=100)),
                ('Esp_Disco_Duro', models.CharField(max_length=100)),
                ('Esp_Tipo_Disco', models.CharField(max_length=50)),
                ('Esp_Sistema_Operativo', models.CharField(max_length=100)),
                ('Esp_Version_SO', models.CharField(max_length=50)),
                ('Esp_Licencia_SO', models.CharField(max_length=100)),
                ('Esp_Memoria_RAM', models.CharField(max_length=50)),
                ('Esp_Tarjeta_Video', models.CharField(max_length=100)),
                ('Esp_Conectividad_Red', models.CharField(default='Ninguna', max_length=100)),
                ('Esp_Estado_Bateria', models.CharField(max_length=50)),
                ('Esp_SO_Actualizado', models.BooleanField(default=False)),
                ('Esp_Antivirus', models.CharField(blank=True, max_length=100)),
                ('Esp_Antivirus_Actualizado', models.BooleanField(default=False)),
                ('Esp_Estado_Equipo', models.CharField(max_length=100)),
                ('Esp_Observaciones', models.TextField(blank=True)),
                ('Esp_Software_Instalado', models.TextField(blank=True, verbose_name='Software Instalado')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificacionesequipo', to='chequeos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Chequeo',
            fields=[
                ('Id_Chequeo', models.AutoField(primary_key=True, serialize=False)),
                ('Che_Fecha_Chequeo', models.DateField()),
                ('Che_Observaciones', models.TextField(blank=True, null=True)),
                ('Id_Equipo', models.ForeignKey(db_column='Id_Equipo', on_delete=django.db.models.deletion.CASCADE, related_name='chequeos', to='chequeos.equipo')),
                ('Id_Usuario', models.ForeignKey(db_column='Id_Usuario', on_delete=django.db.models.deletion.CASCADE, related_name='chequeos', to='chequeos.usuario')),
                ('software_instalado', models.ManyToManyField(blank=True, to='chequeos.software')),
            ],
        ),
    ]
