# Generated by Django 4.2.23 on 2025-07-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chequeos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especificacionesequipo',
            old_name='Id_Equipo',
            new_name='Equipo',
        ),
        migrations.DeleteModel(
            name='EquipoSoftware',
        ),
    ]
