# Generated by Django 4.2.23 on 2025-07-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chequeos', '0002_rename_id_equipo_especificacionesequipo_equipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionesequipo',
            name='Id_Especificacion',
        ),
        migrations.AlterField(
            model_name='especificacionesequipo',
            name='Equipo',
            field=models.OneToOneField(db_column='Id_Equipo', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chequeos.equipo'),
        ),
        migrations.AlterModelTable(
            name='especificacionesequipo',
            table='chequeos_especificacionesequipo',
        ),
    ]
