# Generated by Django 4.2.23 on 2025-07-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chequeos', '0003_remove_especificacionesequipo_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionesequipo',
            name='Esp_Antivirus',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('No aplica', 'No aplica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='especificacionesequipo',
            name='Esp_Antivirus_Actualizado',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('No aplica', 'No aplica')], max_length=20),
        ),
        migrations.AlterField(
            model_name='especificacionesequipo',
            name='Esp_SO_Actualizado',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No'), ('No aplica', 'No aplica')], max_length=20),
        ),
    ]
