# Generated by Django 4.2.23 on 2025-07-14 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chequeos', '0004_alter_especificacionesequipo_esp_antivirus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionesequipo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
