# Generated by Django 4.2.23 on 2025-07-14 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chequeos', '0006_alter_especificacionesequipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='Id_Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to=settings.AUTH_USER_MODEL),
        ),
    ]
