# Generated by Django 4.2.23 on 2025-07-14 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chequeos', '0007_equipo_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='Id_Usuario',
        ),
        migrations.AlterField(
            model_name='especificacionesequipo',
            name='equipo',
            field=models.OneToOneField(db_column='Id_Equipo', on_delete=django.db.models.deletion.CASCADE, related_name='especificacionesequipo', to='chequeos.equipo'),
        ),
        migrations.AlterModelTable(
            name='especificacionesequipo',
            table='chequeos_especificacionesequipo',
        ),
    ]
