# Generated by Django 4.2.23 on 2025-07-14 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chequeos', '0008_remove_equipo_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionesequipo',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especificacionesequipo', to='chequeos.equipo'),
        ),
        migrations.AlterModelTable(
            name='especificacionesequipo',
            table=None,
        ),
    ]
