# Generated by Django 4.2.23 on 2025-07-14 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chequeos', '0009_alter_especificacionesequipo_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionesequipo',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='Id_Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
