# Generated by Django 4.2.23 on 2025-07-15 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chequeos', '0010_alter_especificacionesequipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Equ_Placa_Serie',
            field=models.CharField(help_text='Ej: PCNJ-OFIMAT001. Hasta 15 caracteres.', max_length=15, validators=[django.core.validators.RegexValidator(message='Máximo 15 caracteres. Solo letras, números, guiones (-) y asteriscos (*).', regex='^[A-Za-z0-9\\-\\*]{1,15}$')], verbose_name='Placa Equ Serie'),
        ),
    ]
