# Generated by Django 4.2.23 on 2025-07-15 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chequeos', '0011_alter_equipo_equ_placa_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Equ_Placa_Serie',
            field=models.CharField(help_text='Ej: PCNJ-OFIMAT001. Máx. 15 caracteres.', max_length=15, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, números, guiones (-) y asteriscos (*), hasta 15 caracteres.', regex='^[A-Za-z0-9\\-\\*]{1,15}$')]),
        ),
    ]
