# Generated by Django 5.2.4 on 2025-07-17 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chequeos', '0012_alter_equipo_equ_placa_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Equ_Placa_Serie',
            field=models.CharField(help_text='máximo 15 caracteres.', max_length=15, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras, números, guiones (-) y asteriscos (*), hasta 15 caracteres.', regex='^[A-Za-z0-9\\-\\*]{1,15}$')]),
        ),
    ]
